# @package _global_
name: sysevr

sensi_api_path: resources/sensiAPI.txt
no_api_path: resources/noAPI.txt


dataset:
  name: example
  token:
    max_parts: 50
    is_wrapped: false
    is_splitted: false
    vocabulary_size: 190000

encoder:
  embedding_size: 50
  rnn_size: 256
  use_bi_rnn: true
  rnn_num_layers: 1
  rnn_dropout: 0.2

classifier:
  n_hidden_layers: 2
  hidden_size: 500
  classifier_input_size: 300
  activation: tanh

hyper_parameters:
  vector_length: 50
  seq_len: 50
  n_epochs: 20
  patience: 5
  reload_dataloader: true
  batch_size: 16
  test_batch_size: 16
  clip_norm: 0
  random_context: true
  shuffle_data: true

  optimizer: "Adamax"
  learning_rate: 0.002
