# @package _global_
name: vgdetector

dataset:
  name: example
  token:
    max_parts: 50
    is_wrapped: false
    is_splitted: false
    vocabulary_size: 190000
gnn:
  hidden_size: 128
  pooling_ratio: 0.8
  layer_num: 3

classifier:
  hidden_size: 256
  n_hidden_layers: 2
  drop_out: 0.5
  classifier_input_size: 64
  activation: relu

hyper_parameters:
  vector_length: 128

  n_epochs: 50
  patience: 10
  batch_size: 64
  test_batch_size: 64
  reload_dataloader: true
  clip_norm: 0
  random_context: true
  shuffle_data: true

  optimizer: "Adam"
  nesterov: true
  learning_rate: 0.002
  weight_decay: 0
  decay_gamma: 0.95